name: CI

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: deno-v1-${{ hashFiles('deno.lock') }}

      - uses: jurassiscripts/setup-velociraptor@v2
        with:
          checkout: false
          deno-version: 1.x
          velociraptor-version: 1.5.0

      - name: Lint
        run: vr lint

      - name: Test
        run: vr test

      - name: Compile
        run: vr compile
