name: CI

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - uses: jurassiscripts/setup-velociraptor@v2
        with:
          checkout: false
          deno-version: false
          velociraptor-version: 1.5.0

      - name: Lint
        run: vr lint

      - name: Test
        run: vr test

      - name: Compile
        run: vr compile
