name: CI

on:
  push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - uses: actions/cache@v3
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: deno-v1-${{ hashFiles('deno.lock') }}

      - run: deno install -fqA -n vr https://deno.land/x/velociraptor@1.5.0/cli.ts

      - name: Lint
        run: vr lint

      - name: Test
        run: vr test

      - name: Compile
        run: vr compile
